# Generated by Django 5.2.5 on 2025-11-04 18:12

import django.db.models.deletion
import django.utils.timezone
import spaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Campus')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Espaço',
                'verbose_name_plural': 'Tipos de Espaço',
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('plan_image', models.ImageField(upload_to='floor_plans/', verbose_name='Planta')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.building', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('capacity', models.IntegerField(verbose_name='Capacidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('location_x', models.FloatField(blank=True, null=True)),
                ('location_y', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.building', verbose_name='Campus')),
                ('floor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaces.floorplan', verbose_name='Andar')),
                ('space_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.spacetype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora Início')),
                ('end_time', models.TimeField(default=spaces.models.get_default_end_time, verbose_name='Hora Fim')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Reserva Recorrente')),
                ('recurring_days', models.TextField(blank=True, null=True, verbose_name='Dias da Semana')),
                ('recurring_start_date', models.DateField(blank=True, null=True, verbose_name='Data Início Recorrência')),
                ('recurring_end_date', models.DateField(blank=True, null=True, verbose_name='Data Fim Recorrência')),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='Hora Início Segunda')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Segunda')),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='Hora Início Terça')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Terça')),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='Hora Início Quarta')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Quarta')),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='Hora Início Quinta')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Quinta')),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='Hora Início Sexta')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Sexta')),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='Hora Início Sábado')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Sábado')),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='Hora Início Domingo')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Domingo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
