# Generated by Django 5.2.5 on 2025-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='recurring_times',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Horários Recorrentes'),
        ),
    ]
