# Generated by Django 5.2.5 on 2025-10-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='plan_image_url',
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.building', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/', verbose_name='Planta'),
        ),
    ]
