# Generated by Django 5.2.5 on 2025-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_reservation_recurring_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmado', 'Confirmado'), ('canceled', 'Cancelado'), ('completed', 'Concluído')], default='confirmado', max_length=20),
        ),
    ]
