# Generated by Django 5.2.5 on 2025-10-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_floorplan_plan_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.building', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='space',
            name='floor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.floorplan', verbose_name='Andar'),
        ),
        migrations.AlterField(
            model_name='space',
            name='location_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Posição X'),
        ),
        migrations.AlterField(
            model_name='space',
            name='location_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Posição Y'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaces.spacetype', verbose_name='Tipo de Sala'),
        ),
    ]
