# Generated by Django 5.2.5 on 2025-10-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_space_building_alter_space_floor_name_and_more'),
    ]

    operations = [
    ]
