# Generated by Django 5.2.5 on 2025-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmado', 'Confirmado'), ('canceled', 'Cancelado'), ('completed', 'Concluído')], default='confirmado', max_length=20, verbose_name='Status'),
        ),
    ]
