# Generated by Django 5.2.5 on 2025-10-28 12:25

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import spaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_auto_20251028_0922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='building',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=spaces.models.get_default_end_time, verbose_name='Hora Fim'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurring_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')]), blank=True, null=True, size=None, verbose_name='Dias da Semana'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim da Recorrência'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurring_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início da Recorrência'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora Início'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Reserva Recorrente'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
