# Generated by Django 5.2.5 on 2025-10-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_remove_reservation_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='recurring_days',
            field=models.TextField(blank=True, help_text='Dias da semana separados por vírgula (0-6)', null=True, verbose_name='Dias da Semana'),
        ),
    ]
