# Generated by Django 5.2.5 on 2025-10-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_reservation_phone_alter_reservation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
