# Generated by Django 5.2.5 on 2025-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_alter_reservation_recurring_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='building',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='building',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Campus'),
        ),
        migrations.AlterModelTable(
            name='building',
            table=None,
        ),
    ]
