# Generated by Django 5.2.5 on 2025-10-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0010_alter_floor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='space',
            name='floor',
        ),
        migrations.AlterField(
            model_name='space',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.building'),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaces.spacetype'),
        ),
    ]
