# Generated by Django 5.2.5 on 2025-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0011_remove_floor_from_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='floor_name',
            field=models.CharField(max_length=50),
        ),
    ]
